---
.travis.yml:
  secure: "ipVC3UC/g0YqMIXNhsGWFt3/UWla0pe2r3KM7oK+oWmIDCCNqVvjeK2fyWLlLW17yLKiL6xqGY/XBMpF3nNOl6eeUvydcQLn4Nyqf1tQZeg0u8qvYQql5dRZb8kmslj1XI6Ghg7OIz3Am/eDgVudKtkm3gct/o2T0qYtXy0SJQsCFs8ZbkE7nxBu2SihszZxYM1gtAnzsv/f+SOasFxeEli2Nj2TAWK3VWIpj7vG4iyV0WTW6oMgFxW71/Hx/UGR2KUz4mAGW4EEKBXp0U0Znmst1TD0QBi6itV3rigstko0b6GqHok7ay/s0NTxMQaXYkLwazZ5BEqlrE0I6Aggd5RhqyYJu0l7OAqHT4WZ6N9JcvGkKvBnUzILe0xaawwCeNcxMTqIB+HRmGgODZSY0agxg1CyR1ULo+r1c7+8GreTJo2HSvyKFouOhKyn8PctM3+W5Npr3Rtm11h3WmhwKq6IfJ0392+ROTyIx2Ht4801ne0bwTqZ3AJdmHWFgfQA4zH5aAg83du4kXCHqZyVqv+ZdHxzTBqRh/k2mZz+Xc0MD85FAhlgvTifkanvHNFQavRwkhXuRm5IxqXlQqACNyKJGojohEMqL/tIfr85rHRIekfs65/bmPFZocAlj3rcy++YkVg3dKtHRUVufIBy3tCsygcfZ78e0wLE6vQOpiA="
  docker_sets:
    - set: centos6-64
    - set: centos7-64
    - set: centos8-64

spec/spec_helper_acceptance.rb:
  unmanaged: false
